#!/usr/bin/python3

import pdmt.mgr # for Mgr

mgr=pdmt.mgr.Mgr.new_manager()
mgr.load_all_plugins()

# mako stuff
for name in pdmt.helper.walk_regexp('templartmp', '*.mako'):
	# remove the prefix folder and the suffix to create the target
	target_file_name=None
	mgr.add_node(pdmt.plugins.nodes.makofile.NodeType(name=name))
	mgr.add_node(pdmt.plugins.nodes.makotfile.NodeType(name=name))
	mgr.add_edge()

mgr.parseCmdline()

mgr.shutdown()
